version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  cache:
services:
  redis:
    image: redis:3.2
    networks:
      - cache
  postgres: # Container para banco de dados
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend: # Container para front-end
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/
      # Conf. proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - web
    depends_on:
      - app
  app: # Container para backend
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8081:8081
    networks:
      - banco
      - web
      - cache
    depends_on:
      - db
